name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      petclinic:
        image: springcommunity/spring-petclinic
        ports:
          - 8080:8080
        options: >-
          --health-cmd="curl -f http://localhost:8080 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for PetClinic to be healthy
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/petclinic/api/owners; then
              echo "PetClinic is up!"
              break
            fi
            echo "Waiting for PetClinic..."
            sleep 5
          done

      - name: Build with Maven
        run: ./mvnw clean test
